version: '2.4'

services:
  nodejs-auth:
    build:
      context: .
      args:
        - NODE_ENV=development
    image: nodejs
    container_name: auth-api
    restart: unless-stopped
    command: npm run dev
    ports:
      - "4000:4000"
    volumes:
      - .:/opt/node_app/app
      - ./package.json:/opt/node_app/package.json
      - ./package-lock.json:/opt/node_app/package-lock.json
      - notused:/opt/node_app/app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=mongo
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=example-database
    depends_on:
      mongo:
        condition: service_healthy

  mongo:
    image: mongo:4
    container_name: mongo-auth-api
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./database/seed.js:/docker-entrypoint-initdb.d/seed.js
    healthcheck:
      test: "[ `echo 'db.runCommand(\"ping\").ok' | mongo localhost/example-database --quiet` ] && echo 0 || echo 1"
      interval: 5s
      timeout: 10s
      retries: 3

volumes:
  notused:
